<?php

declare(strict_types=1);

namespace SzepeViktor\PHPStan\WordPress\Tests;

// These should not be reported as errors by PHPStan's ConstantRule
use const ABSPATH;
use const WP_CONTENT_DIR;
use const WP_LANG_DIR;
use const WPMU_PLUGIN_DIR;
use const WP_PLUGIN_DIR;
use const WP_DEBUG;
use const WP_DEBUG_LOG;
use const WP_DEBUG_DISPLAY;
use const EMPTY_TRASH_DAYS;
use const SCRIPT_DEBUG;
use const COOKIE_DOMAIN;
use const WP_DEFAULT_THEME;
use const MINUTE_IN_SECONDS;
use const HOUR_IN_SECONDS;
use const DAY_IN_SECONDS;
use const WEEK_IN_SECONDS;
use const MONTH_IN_SECONDS;
use const YEAR_IN_SECONDS;
use const KB_IN_BYTES;
use const MB_IN_BYTES;
use const GB_IN_BYTES;
use const TB_IN_BYTES;
use const PB_IN_BYTES;
use const EB_IN_BYTES;
use const OBJECT;
use const OBJECT_K;
use const ARRAY_A;
use const ARRAY_N;
use const EP_NONE;
use const EP_PERMALINK;
use const EP_ATTACHMENT;
use const EP_DATE;
use const EP_YEAR;
use const EP_MONTH;
use const EP_DAY;
use const EP_ROOT;
use const EP_COMMENTS;
use const EP_SEARCH;
use const EP_CATEGORIES;
use const EP_TAGS;
use const EP_AUTHORS;
use const EP_PAGES;
use const EP_ALL_ARCHIVES;
use const EP_ALL;
use const FS_CONNECT_TIMEOUT;
use const FS_TIMEOUT;
use const FS_CHMOD_DIR;
use const FS_CHMOD_FILE;

// These should not be reported as errors by PHPStan's ConstantRule and RequireFileExistsRule
require_once ABSPATH . 'file.php';
require_once WP_PLUGIN_DIR . '/file.php';
require_once WP_CONTENT_DIR . '/file.php';
require_once WP_LANG_DIR . '/file.php';
require_once WPMU_PLUGIN_DIR . '/file.php';

// These should not be reported as errors by PHPStan's ConstantRule
$testVariable = ABSPATH;
$testVariable = WP_CONTENT_DIR;
$testVariable = WP_LANG_DIR;
$testVariable = WPMU_PLUGIN_DIR;
$testVariable = WP_PLUGIN_DIR;
$testVariable = WP_DEBUG_LOG;
$testVariable = WP_DEBUG;
$testVariable = WP_DEBUG_DISPLAY;
$testVariable = WP_DEFAULT_THEME;
$testVariable = EMPTY_TRASH_DAYS;
$testVariable = SCRIPT_DEBUG;
$testVariable = COOKIE_DOMAIN;
$testVariable = MINUTE_IN_SECONDS;
$testVariable = HOUR_IN_SECONDS;
$testVariable = DAY_IN_SECONDS;
$testVariable = WEEK_IN_SECONDS;
$testVariable = MONTH_IN_SECONDS;
$testVariable = YEAR_IN_SECONDS;
$testVariable = KB_IN_BYTES;
$testVariable = MB_IN_BYTES;
$testVariable = GB_IN_BYTES;
$testVariable = TB_IN_BYTES;
$testVariable = PB_IN_BYTES;
$testVariable = EB_IN_BYTES;
$testVariable = OBJECT;
$testVariable = OBJECT_K;
$testVariable = ARRAY_A;
$testVariable = ARRAY_N;
$testVariable = EP_NONE;
$testVariable = EP_PERMALINK;
$testVariable = EP_ATTACHMENT;
$testVariable = EP_DATE;
$testVariable = EP_YEAR;
$testVariable = EP_MONTH;
$testVariable = EP_DAY;
$testVariable = EP_ROOT;
$testVariable = EP_COMMENTS;
$testVariable = EP_SEARCH;
$testVariable = EP_CATEGORIES;
$testVariable = EP_TAGS;
$testVariable = EP_AUTHORS;
$testVariable = EP_PAGES;
$testVariable = EP_ALL_ARCHIVES;
$testVariable = EP_ALL;
$testVariable = FS_CONNECT_TIMEOUT;
$testVariable = FS_TIMEOUT;
$testVariable = FS_CHMOD_DIR;
$testVariable = FS_CHMOD_FILE;
